name: Documentation
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: zensical build --clean
      
      # --- NOTIFICAÇÃO DE ERRO ---
      - name: Notificar falha via ntfy
        if: failure()
        run: |
          curl \
            -H "Title: Erro no Build de ${{ github.repository }}" \
            -H "Priority: high" \
            -H "Tags: x" \
            -d "O workflow de documentação do repositório ${{ github.repository }} FALHOU." \
            -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
            https://ntfy.giobon.uk/transpeed

      # Estas etapas só rodarão se as anteriores passarem com sucesso
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment
